monitor.bluez.properties = {
  bluez5.enable-hw-volume = false
  bluez5.enable-absolute-volume = false
}

monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.enable-hw-volume = false
        bluez5.enable-absolute-volume = false
      }
    }
  },
  {
    matches = [
      {
        node.name = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.enable-hw-volume = false
        bluez5.enable-absolute-volume = false
      }
    }
  }
]
