#include ./kitty-themes/00-Default.conf
#include ./kitty-themes/Brogrammer.conf
include ./theme.conf
include ./dank-tabs.conf
#include ./catppuccin-mocha.conf

shell /usr/bin/fish

#font_family CaskaydiaCove Nerd Font Mono
#font_family JetBrainsMono Nerd Font Mono
font_family MesloLGS Nerd Font
font_size 14.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.95
#dynamic_background_opacity yes
confirm_os_window_close 0
hide_window_decorations no

focus_follows_mouse no

# Animated cursor
cursor_trail 1

# change to x11 or wayland or leave auto
linux_display_server auto

# Automatically copy selected text to the system clipboard
copy_on_select clipboard

# Make a right-click paste from the clipboard (optional, but highly recommended)
mouse_map right press ungrabbed paste_from_clipboard

scrollback_lines 10000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

#foreground #dddddd
#background #000000
#cursor #dddddd

# ==========================================
# --- TABS & SPLITS (PANES) KEYBINDINGS ---
# ==========================================

# Layouts
enabled_layouts splits,stack

# Tabs
map ctrl+shift+t new_tab
map ctrl+page_down next_tab
map ctrl+page_up previous_tab

# Splits (Panes)
map ctrl+shift+o launch --location=vsplit --cwd=current
map ctrl+shift+e launch --location=hsplit --cwd=current
map ctrl+shift+w close_window

# Split Navigation (Ctrl + Arrow Keys)
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# Toggle Zoom / Fullscreen Pane
map ctrl+shift+enter toggle_layout stack

# Resizing Splits (Ctrl + Shift + Arrow Keys)
map ctrl+shift+left resize_window narrower 3
map ctrl+shift+right resize_window wider 3
map ctrl+shift+up resize_window shorter 3
map ctrl+shift+down resize_window taller 3

