# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #161E25
background         #FFFEFD
cursor             #496077

active_tab_foreground     #FFFEFD
active_tab_background     #161E25
inactive_tab_foreground   #161E25
inactive_tab_background   #FFFEFD

active_border_color   #161E25
inactive_border_color #FFFEFD
bell_border_color     #496684

color0      #FFFEFD
color1		#496684
color2		#5C7997
color3		#756758
color4		#13548F
color5		#25323E
color6		#25323E
color7		#161E25
color8		#958B86
color9		#6288B0
color10		#7BA2C9
color11		#9C8975
color12		#1970BF
color13		#314253
color14		#314253
color15		#070A0C
