[colors]
background = '#13121c'
foreground = '#e5e0ef'

cursor_bg = '#c7bfff'
cursor_fg = '#13121c'
cursor_border = '#c7bfff'

selection_bg = '#3e00dd'
selection_fg = '#e5e0ef'

ansi = ['#13121c', '#ff7292', '#7fff98', '#ffd972', '#b2a9f2', '#463f76', '#c7bfff', '#f1efff']
brights = ['#9a99a5', '#ff9fb4', '#a5ffb7', '#ffe7a5', '#cfc8ff', '#d7d2ff', '#e5e2ff', '#f9f8ff']
