[colors]
background = '#111317'
foreground = '#e2e2e8'

cursor_bg = '#a8c8ff'
cursor_fg = '#111317'
cursor_border = '#a8c8ff'

selection_bg = '#6992d3'
selection_fg = '#e2e2e8'

ansi = ['#111317', '#ff729a', '#7fff92', '#fff872', '#8fb3f2', '#2c4776', '#a8c8ff', '#eff5ff']
brights = ['#999da5', '#ff9fba', '#a5ffb2', '#fffaa5', '#b5d0ff', '#c2d8ff', '#d7e6ff', '#f8faff']
