[colors.primary]
background = '#111317'
foreground = '#e2e2e8'

[colors.selection]
text = '#e2e2e8'
background = '#6992d3'

[colors.cursor]
text = '#111317'
cursor = '#a8c8ff'

[colors.normal]
black   = '#111317'
red     = '#ff729a'
green   = '#7fff92'
yellow  = '#fff872'
blue    = '#8fb3f2'
magenta = '#2c4776'
cyan    = '#a8c8ff'
white   = '#eff5ff'

[colors.bright]
black   = '#999da5'
red     = '#ff9fba'
green   = '#a5ffb2'
yellow  = '#fffaa5'
blue    = '#b5d0ff'
magenta = '#c2d8ff'
cyan    = '#d7e6ff'
white   = '#f8faff'
