[colors.primary]
background = '#13121c'
foreground = '#e5e0ef'

[colors.selection]
text = '#e5e0ef'
background = '#3e00dd'

[colors.cursor]
text = '#13121c'
cursor = '#c7bfff'

[colors.normal]
black   = '#13121c'
red     = '#ff7292'
green   = '#7fff98'
yellow  = '#ffd972'
blue    = '#b2a9f2'
magenta = '#463f76'
cyan    = '#c7bfff'
white   = '#f1efff'

[colors.bright]
black   = '#9a99a5'
red     = '#ff9fb4'
green   = '#a5ffb7'
yellow  = '#ffe7a5'
blue    = '#cfc8ff'
magenta = '#d7d2ff'
cyan    = '#e5e2ff'
white   = '#f9f8ff'
