-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("dms ipc call defaultApp browser"), { description = "Default Web Browser: Open" })
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("dms ipc call control-center toggle"), { description = "Control Center: Toggle" })
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("dms ipc call dash toggle \"\""), { description = "Dashboard: Toggle" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("dms ipc call defaultApp fileManager"), { description = "Default File Manager: Open" })
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "dms ipc call powermenu toggle" })
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { description = "Spotlight Bar: Toggle" })
hl.unbind("SUPER + SHIFT + J")
hl.bind("SUPER + SHIFT + J", hl.dsp.exec_cmd("dms ipc call window-rules toggle"), { description = "dms ipc call window-rules toggle" })
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("dms ipc call wallpaper next"), { description = "Wallpaper: Next" })
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { description = "Spotlight Bar: Toggle" })
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.exec_cmd("ghostty"), { description = "Launch Ghostty" })
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.exec_cmd("kitty"), { description = "Launch Kitty" })
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("pavucontrol"))
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("alacritty"), { description = "Launch Alacritty" })
hl.unbind("ALT + space")
hl.unbind("CTRL + space")
hl.unbind("SUPER + A")
hl.unbind("SUPER + H")
hl.unbind("SUPER + J")
hl.bind("SUPER + J", hl.dsp.group.toggle(), { description = "togglegroup" })
hl.unbind("SUPER + L")
hl.unbind("SUPER + Return")
hl.unbind("SUPER + SHIFT + E")
hl.unbind("SUPER + SHIFT + Q")
hl.unbind("SUPER + SHIFT + T")
hl.unbind("SUPER + X")
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.window.float({ action = "toggle" }), { description = "Float/unfloat window" })
hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("dms ipc call wallpaper prev"), { description = "Wallpaper: Previous" })
