-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-2", mode = "2560x1600@239.999", position = "2560x0", scale = 1, vrr = 1 })
hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "eDP-1", mode = "1920x1080@60.001", position = "0x0", scale = 1, vrr = 0, bitdepth = 10 })
