[tools]
node = "latest"
pnpm = "latest"
uv = "latest"
go = "latest"
opencode = "latest"
codex = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:composio-core" = "latest"
"npm:firecrawl-cli" = "latest"
"npm:@insforge/cli" = "latest"
"npm:repomix" = "latest"
"npm:tsx" = "latest"
biome = "latest"
gh = "latest"
supabase = "latest"
railway = "latest"
vercel = { version = "latest", trust_policy_excludes = ["fastq"] }
"npm:@withgraphite/graphite-cli" = "latest"
ruff = "latest"
cargo-binstall = "latest"
sccache = "latest"
golangci-lint = "latest"
